<template>
	<div class="tpl cssTpl" style="background-color:pink;">
		<div>
      {{msg}}
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
      <p>88</p>
    </div>
	</div>
</template>
<script>

	export default {
	  name: 'CssTpl',
    methods: {},
    data (){
      return {
        msg:'这个是CSS模板组件',
        success:'css模板加载成功了'
      }
    },
    created(){
      this.$store.commit('nowStatus','end')
      setTimeout(()=>{
        this.$store.commit('nowStatus','hide')
      },800)
    },
    beforeCreate(){
      this.$store.commit('nowStatus','loading')
    },
    mounted(){
      setTimeout(()=>{
        this.$store.commit('nowStatus','normal')
      },1000)
    },
    destroyed(){
      // console.log('Css被销毁了')
    }
	}
</script>
<style scoped></style>